### ISSUE TITLE
Add a way to add a custom proto_path

### ISSUE THREAD

**Issue by Gryfenfer97** [ansys/ansys-tools-protoc-helper#46]
### 📝 Description of the feature

For the moment it is not possible to add a custom proto_path (`--proto_path`).

We are trying to build [ansys-api-mapdl](https://github.com/ansys/ansys-api-mapdl) with files that has been copied from TFS and don't have the same path import format (on github it's `import "ansys/api/mapdl/v0/mapdl.proto"` and on TFS `import "mapdl.proto"`).
We would like to add the argument `--proto_path=ansys/api/mapdl/v0`

Is it possible to find a way to do it?

@RobPasMue @greschd What's your thoughts about it?

**Comment by greschd** [comment]
Hmm, I'm not sure if this is possible. One of the "features" of the protobuf Python generated code is that the resulting Python module structure is determined by the directory structure, see https://protobuf.dev/reference/python/python-generated/#package.
This is different from e.g. C++, where the `package` attribute is used.

So I think this means the `ansys/api/mapdl/v0` directories need to be present in the paths as given to `protoc` for the Python wheel.

So the idea would be to set `--proto_path=ansys/api/mapdl/v0` and then use relative imports, correct? The docs https://protobuf.dev/programming-guides/proto3/#importing recommends _against_ using relative imports

> In general you should set the --proto_path flag to the root of your project and use fully qualified names for all imports

but I'm not sure if that means it _doesn't work_, or simply isn't best practice. Maybe you can test it out by using the `protoc` compiler directly? The important piece to check is whether the resulting Python package includes the `ansys.api.mapdl.v0` structure (it should).

The way we've dealt with this in other projects is the reverse, adding the `ansys/api/<product_name>/vN` directory on the backend side of the proto definition. While that adds a lot of empty directory nesting levels, it has the benefit of making the proto structure consistent across languages.

**Comment by RobPasMue** [comment]
I can only agree with @greschd - documentation recommends to avoid relative imports. Also, other libraries went down the route of creating the subdirectory tree in order to align to the current mechanism - which is more reliable. Thus, unless strictly necessary, I'd avoid doing it.

See https://protobuf.dev/programming-guides/style/#packages - they are recommending your package name to be based on the folder structure you have... And this is the general guidelines, not only the Python ones. So, in order to remain consistent with other Ansys products or libraries, I'd avoid "going solo" with your folder approach. If you ``mapdl`` proto files were to be consumed by other services (let's imagine that the PRIME server ends up supporting talking to the MAPDL server directly through the gRPC interface) - you may enter into import issues even on C++.

**Comment by germa89** [comment]
Well... it is annoying to have to change the proto files between repos but I guess we will have to @Gryfenfer97.

I'm closing the issue then. Thank you a lot for your feedback guys!
